//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VandrarhemDbAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BokningsVy
    {
        public string ForNamn { get; set; }
        public string EfterNamn { get; set; }
        public int RumsNummer { get; set; }
        public int AntalBaddar { get; set; }
        public int KundId { get; set; }
        public System.DateTime InCheckning { get; set; }
        public System.DateTime UtCheckning { get; set; }
    }
}
