//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VandrarhemDbAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bokningar
    {
        public Bokningar()
        {
            this.KundBoknings = new HashSet<KundBokning>();
            this.RumsBoknings = new HashSet<RumsBokning>();
        }
    
        public int BokningsId { get; set; }
        public System.DateTime InCheckning { get; set; }
        public System.DateTime UtCheckning { get; set; }
        public int Betalt { get; set; }
    
        public virtual ICollection<KundBokning> KundBoknings { get; set; }
        public virtual ICollection<RumsBokning> RumsBoknings { get; set; }
    }
}
