//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VandrarhemDbAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class KundBokning
    {
        public int KundBokningsId { get; set; }
        public int KundId { get; set; }
        public int BokningsId { get; set; }
    
        public virtual Bokningar Bokningar { get; set; }
        public virtual Kund Kund { get; set; }
    }
}
