//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VandrarhemDbAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rum
    {
        public Rum()
        {
            this.RumsBoknings = new HashSet<RumsBokning>();
        }
    
        public int RumsId { get; set; }
        public int RumsNummer { get; set; }
        public int AntalBaddar { get; set; }
    
        public virtual ICollection<RumsBokning> RumsBoknings { get; set; }
    }
}
